# See https://tech.davis-hansson.com/p/make/
MAKEFLAGS += --warn-undefined-variables
MAKEFLAGS += --no-builtin-rules

E2E_BOX_BIN = ../box
E2E_BOX = $(E2E_BOX_BIN)

DIFF = diff --strip-trailing-cr --ignore-all-space --side-by-side --suppress-common-lines

DOCKER_RUN = docker run --interactive --platform linux/amd64 --rm --workdir=/opt/box

# Matches the minimum PHP version supported by Composer.
DOCKER_MIN_COMPOSER_PHP_VERSION_IMAGE_TAG = box_php725
DOCKER_MIN_COMPOSER_PHP_VERSION_RUN_COMMAND = $(DOCKER_MIN_COMPOSER_PHP_VERSION_IMAGE_TAG) php index.phar -vvv --no-ansi

# Matches the minimum PHP version supported by Box.
DOCKER_MIN_BOX_PHP_VERSION_IMAGE_TAG = box_php81
DOCKER_MIN_BOX_XDEBUG_PHP_VERSION__IMAGE_TAG = box_php81_xdebug
DOCKER_MIN_BOX_PHP_VERSION_RUN_COMMAND = $(DOCKER_MIN_BOX_PHP_VERSION_IMAGE_TAG) php index.phar -vvv --no-ansi

E2E_TEST_PASS_NO_CONFIG_DIR := fixtures/pass-no-config
E2E_TEST_PASS_NO_CONFIG_VENDOR := $(E2E_TEST_PASS_NO_CONFIG_DIR)/vendor
E2E_TEST_PASS_NO_CONFIG_PHAR := $(E2E_TEST_PASS_NO_CONFIG_DIR)/index.phar
E2E_TEST_PASS_NO_CONFIG_MIN_COMPOSER_EXPECTED_OUTPUT := $(E2E_TEST_PASS_NO_CONFIG_DIR)/expected-output-725
E2E_TEST_PASS_NO_CONFIG_MIN_COMPOSER_EXPECTED_OUTPUT_TEMPLATE := $(E2E_TEST_PASS_NO_CONFIG_DIR)/expected-output-725-dist
E2E_TEST_PASS_NO_CONFIG_MIN_BOX_EXPECTED_OUTPUT := $(E2E_TEST_PASS_NO_CONFIG_DIR)/expected-output-current-min-php
E2E_TEST_PASS_NO_CONFIG_MIN_BOX_EXPECTED_OUTPUT_TEMPLATE := $(E2E_TEST_PASS_NO_CONFIG_DIR)/expected-output-current-min-php-dist
E2E_TEST_PASS_NO_CONFIG_ACTUAL_OUTPUT := $(E2E_TEST_PASS_NO_CONFIG_DIR)/actual-output

E2E_TEST_PASS_COMPLETE_DIR := fixtures/pass-complete
E2E_TEST_PASS_COMPLETE_VENDOR := $(E2E_TEST_PASS_COMPLETE_DIR)/vendor
E2E_TEST_PASS_COMPLETE_PHAR := $(E2E_TEST_PASS_COMPLETE_DIR)/index.phar
E2E_TEST_PASS_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT := $(E2E_TEST_PASS_COMPLETE_DIR)/expected-output-725
E2E_TEST_PASS_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT_TEMPLATE := $(E2E_TEST_PASS_COMPLETE_DIR)/expected-output-725-dist
E2E_TEST_PASS_COMPLETE_MIN_BOX_EXPECTED_OUTPUT := $(E2E_TEST_PASS_COMPLETE_DIR)/expected-output-current-min-php
E2E_TEST_PASS_COMPLETE_MIN_BOX_EXPECTED_OUTPUT_TEMPLATE := $(E2E_TEST_PASS_COMPLETE_DIR)/expected-output-current-min-php-dist
E2E_TEST_PASS_COMPLETE_ACTUAL_OUTPUT := $(E2E_TEST_PASS_COMPLETE_DIR)/actual-output

E2E_TEST_FAIL_COMPLETE_DIR := fixtures/fail-complete
E2E_TEST_FAIL_COMPLETE_VENDOR := $(E2E_TEST_FAIL_COMPLETE_DIR)/vendor
E2E_TEST_FAIL_COMPLETE_PHAR := $(E2E_TEST_FAIL_COMPLETE_DIR)/index.phar
E2E_TEST_FAIL_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT := $(E2E_TEST_FAIL_COMPLETE_DIR)/expected-output-725
E2E_TEST_FAIL_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT_TEMPLATE := $(E2E_TEST_FAIL_COMPLETE_DIR)/expected-output-725-dist
E2E_TEST_FAIL_COMPLETE_MIN_BOX_EXPECTED_OUTPUT := $(E2E_TEST_FAIL_COMPLETE_DIR)/expected-output-current-min-php
E2E_TEST_FAIL_COMPLETE_MIN_BOX_EXPECTED_OUTPUT_TEMPLATE := $(E2E_TEST_FAIL_COMPLETE_DIR)/expected-output-current-min-php-dist
E2E_TEST_FAIL_COMPLETE_ACTUAL_OUTPUT := $(E2E_TEST_FAIL_COMPLETE_DIR)/actual-output

E2E_TEST_SKIP_DIR := fixtures/fail-complete
E2E_TEST_SKIP_VENDOR := $(E2E_TEST_SKIP_DIR)/vendor
E2E_TEST_SKIP_PHAR := $(E2E_TEST_SKIP_DIR)/index.phar
E2E_TEST_SKIP_MIN_COMPOSER_EXPECTED_OUTPUT := $(E2E_TEST_SKIP_DIR)/expected-output-725-skipped
E2E_TEST_SKIP_MIN_COMPOSER_EXPECTED_OUTPUT_TEMPLATE := $(E2E_TEST_SKIP_DIR)/expected-output-725-skipped-dist
E2E_TEST_SKIP_ACTUAL_OUTPUT := $(E2E_TEST_SKIP_DIR)/actual-output


#
# Pass No Config
#---------------------------------------------------------------------------

.PHONY: test_e2e_pass_no_config_min_composer_php
test_e2e_pass_no_config_min_composer_php: docker_images _test_e2e_pass_no_config_min_composer_php

.PHONY: _test_e2e_pass_no_config_min_composer_php
_test_e2e_pass_no_config_min_composer_php: $(E2E_TEST_PASS_NO_CONFIG_PHAR)
	@echo "$(YELLOW_COLOR)Test RequirementChecker with a project with no configuration (min PHP version supported by Composer).$(NO_COLOR)"
	@rm $(E2E_TEST_PASS_NO_CONFIG_ACTUAL_OUTPUT) $(E2E_TEST_PASS_NO_CONFIG_MIN_COMPOSER_EXPECTED_OUTPUT) || true
	@$(MAKE) $(E2E_TEST_PASS_NO_CONFIG_MIN_COMPOSER_EXPECTED_OUTPUT)

	$(DOCKER_RUN) \
		--volume="$$PWD/$(E2E_TEST_PASS_NO_CONFIG_DIR)":/opt/box \
		$(DOCKER_MIN_COMPOSER_PHP_VERSION_RUN_COMMAND) \
		2>&1 | tee $(E2E_TEST_PASS_NO_CONFIG_ACTUAL_OUTPUT)
	$(DIFF) \
		$(E2E_TEST_PASS_NO_CONFIG_MIN_COMPOSER_EXPECTED_OUTPUT) \
		$(E2E_TEST_PASS_NO_CONFIG_ACTUAL_OUTPUT)


.PHONY: test_e2e_pass_no_config_min_box_php
test_e2e_pass_no_config_min_box_php: docker_images _test_e2e_pass_no_config_min_box_php

.PHONY: _test_e2e_pass_no_config_min_box_php
_test_e2e_pass_no_config_min_box_php: $(E2E_TEST_PASS_NO_CONFIG_PHAR)
	@echo "$(YELLOW_COLOR)Test RequirementChecker with a project with no configuration (min PHP version supported by Box).$(NO_COLOR)"
	@rm $(E2E_TEST_PASS_NO_CONFIG_ACTUAL_OUTPUT) $(E2E_TEST_PASS_NO_CONFIG_MIN_BOX_EXPECTED_OUTPUT) || true
	@$(MAKE) $(E2E_TEST_PASS_NO_CONFIG_MIN_BOX_EXPECTED_OUTPUT)

	$(DOCKER_RUN) \
		--volume="$$PWD/$(E2E_TEST_PASS_NO_CONFIG_DIR)":/opt/box \
		$(DOCKER_MIN_BOX_PHP_VERSION_RUN_COMMAND) \
		2>&1 | tee $(E2E_TEST_PASS_NO_CONFIG_ACTUAL_OUTPUT)
	$(DIFF) \
		$(E2E_TEST_PASS_NO_CONFIG_MIN_BOX_EXPECTED_OUTPUT) \
		$(E2E_TEST_PASS_NO_CONFIG_ACTUAL_OUTPUT)


#
# Pass Complete
#---------------------------------------------------------------------------

.PHONY: test_e2e_pass_complete_min_composer_php
test_e2e_pass_complete_min_composer_php: docker_images _test_e2e_pass_complete_min_composer_php

.PHONY: _test_e2e_pass_complete_min_composer_php
_test_e2e_pass_complete_min_composer_php: $(E2E_TEST_PASS_COMPLETE_PHAR)
	@echo "$(YELLOW_COLOR)Test RequirementChecker with a project with satisfied requirements (min PHP version supported by Composer).$(NO_COLOR)"
	@rm $(E2E_TEST_PASS_COMPLETE_ACTUAL_OUTPUT) $(E2E_TEST_PASS_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT) || true
	@$(MAKE) $(E2E_TEST_PASS_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT)

	$(DOCKER_RUN) \
		--volume="$$PWD/$(E2E_TEST_PASS_COMPLETE_DIR)":/opt/box \
		$(DOCKER_MIN_COMPOSER_PHP_VERSION_RUN_COMMAND) \
		2>&1 | tee $(E2E_TEST_PASS_COMPLETE_ACTUAL_OUTPUT)
	$(DIFF) \
		$(E2E_TEST_PASS_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT) \
		$(E2E_TEST_PASS_COMPLETE_ACTUAL_OUTPUT)


.PHONY: test_e2e_pass_complete_min_box_php
test_e2e_pass_complete_min_box_php: docker_images _test_e2e_pass_complete_min_box_php

CCYELLOW = \033[0;33m
CCEND = \033[0m
.PHONY: _test_e2e_pass_complete_min_box_php
_test_e2e_pass_complete_min_box_php: $(E2E_TEST_PASS_COMPLETE_PHAR)
	@echo "$(YELLOW_COLOR)Test RequirementChecker with a project with satisfied requirements (min PHP version supported by Box).$(NO_COLOR)"
	@rm $(E2E_TEST_PASS_COMPLETE_ACTUAL_OUTPUT) $(E2E_TEST_PASS_COMPLETE_MIN_BOX_EXPECTED_OUTPUT) || true
	@$(MAKE) $(E2E_TEST_PASS_COMPLETE_MIN_BOX_EXPECTED_OUTPUT)

	$(DOCKER_RUN) \
		--volume="$$PWD/$(E2E_TEST_PASS_COMPLETE_DIR)":/opt/box \
		$(DOCKER_MIN_BOX_PHP_VERSION_RUN_COMMAND) \
		2>&1 | tee $(E2E_TEST_PASS_COMPLETE_ACTUAL_OUTPUT)
	$(DIFF) \
		$(E2E_TEST_PASS_COMPLETE_MIN_BOX_EXPECTED_OUTPUT) \
		$(E2E_TEST_PASS_COMPLETE_ACTUAL_OUTPUT)


#
# Fail Complete
#---------------------------------------------------------------------------

.PHONY: test_e2e_fail_complete_min_composer_php
test_e2e_fail_complete_min_composer_php: docker_images _test_e2e_fail_complete_min_composer_php

.PHONY: _test_e2e_fail_complete_min_composer_php
_test_e2e_fail_complete_min_composer_php: $(E2E_TEST_FAIL_COMPLETE_PHAR)
	@echo "$(YELLOW_COLOR)Test RequirementChecker with a project with non-satisfied requirements (min PHP version supported by Composer).$(NO_COLOR)"
	@rm $(E2E_TEST_FAIL_COMPLETE_ACTUAL_OUTPUT) $(E2E_TEST_FAIL_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT) || true
	@$(MAKE) $(E2E_TEST_FAIL_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT)

	$(DOCKER_RUN) \
		--volume="$$PWD/$(E2E_TEST_FAIL_COMPLETE_DIR)":/opt/box \
		$(DOCKER_MIN_COMPOSER_PHP_VERSION_RUN_COMMAND) \
		2>&1 | tee $(E2E_TEST_FAIL_COMPLETE_ACTUAL_OUTPUT)
	$(DIFF) \
		$(E2E_TEST_FAIL_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT) \
		$(E2E_TEST_FAIL_COMPLETE_ACTUAL_OUTPUT)


.PHONY: test_e2e_fail_complete_min_box_php
test_e2e_fail_complete_min_box_php: docker_images _test_e2e_fail_complete_min_box_php

.PHONY: _test_e2e_fail_complete_min_box_php
_test_e2e_fail_complete_min_box_php: $(E2E_TEST_FAIL_COMPLETE_PHAR)
	@echo "$(YELLOW_COLOR)Test RequirementChecker with a project with non-satisfied requirements (min PHP version supported by Box).$(NO_COLOR)"
	@rm $(E2E_TEST_FAIL_COMPLETE_ACTUAL_OUTPUT) $(E2E_TEST_FAIL_COMPLETE_MIN_BOX_EXPECTED_OUTPUT) || true
	@$(MAKE) $(E2E_TEST_FAIL_COMPLETE_MIN_BOX_EXPECTED_OUTPUT)

	$(DOCKER_RUN) \
		--volume="$$PWD/$(E2E_TEST_FAIL_COMPLETE_DIR)":/opt/box \
		$(DOCKER_MIN_BOX_PHP_VERSION_RUN_COMMAND) \
		2>&1 | tee $(E2E_TEST_FAIL_COMPLETE_ACTUAL_OUTPUT)
	$(DIFF) \
		$(E2E_TEST_FAIL_COMPLETE_MIN_BOX_EXPECTED_OUTPUT) \
		$(E2E_TEST_FAIL_COMPLETE_ACTUAL_OUTPUT)


#
# Skip the requirement check
#---------------------------------------------------------------------------

.PHONY: test_e2e_skip_min_composer_php
test_e2e_skip_min_composer_php: docker_images _test_e2e_skip_min_composer_php

.PHONY: _test_e2e_skip_min_composer_php
_test_e2e_skip_min_composer_php: $(E2E_TEST_SKIP_PHAR)
	@echo "$(YELLOW_COLOR)Test skipping the RequirementChecker with a project with non-satisfied requirements.$(NO_COLOR)"
	@rm $(E2E_TEST_SKIP_ACTUAL_OUTPUT) $(E2E_TEST_SKIP_MIN_COMPOSER_EXPECTED_OUTPUT) || true
	@$(MAKE) $(E2E_TEST_SKIP_MIN_COMPOSER_EXPECTED_OUTPUT)

	$(DOCKER_RUN) \
		--env="BOX_REQUIREMENT_CHECKER=0" \
		--volume="$$PWD/$(E2E_TEST_SKIP_DIR)":/opt/box \
		$(DOCKER_MIN_COMPOSER_PHP_VERSION_RUN_COMMAND) \
		2>&1 | tee $(E2E_TEST_SKIP_ACTUAL_OUTPUT)
	$(DIFF) \
		$(E2E_TEST_SKIP_MIN_COMPOSER_EXPECTED_OUTPUT) \
		$(E2E_TEST_SKIP_ACTUAL_OUTPUT)


#
# Rules from files
#---------------------------------------------------------------------------

.PHONY: docker_images
docker_images:
	@# The caching is taken care of within the script
	@./../.docker/build

$(E2E_TEST_PASS_NO_CONFIG_PHAR): $(E2E_BOX_BIN)
	$(E2E_BOX) compile --ansi --working-dir=$(E2E_TEST_PASS_NO_CONFIG_DIR) --no-parallel
	touch -c $(E2E_TEST_PASS_NO_CONFIG_PHAR)
$(E2E_TEST_PASS_NO_CONFIG_PHAR): $(E2E_TEST_PASS_NO_CONFIG_DIR)/index.php $(E2E_TEST_PASS_NO_CONFIG_VENDOR)
$(E2E_TEST_PASS_NO_CONFIG_VENDOR): $(E2E_TEST_PASS_NO_CONFIG_DIR)/composer.lock
$(E2E_TEST_PASS_NO_CONFIG_DIR)/composer.lock: $(E2E_TEST_PASS_NO_CONFIG_DIR)/composer.json
$(E2E_TEST_PASS_NO_CONFIG_MIN_COMPOSER_EXPECTED_OUTPUT): $(E2E_TEST_PASS_NO_CONFIG_MIN_COMPOSER_EXPECTED_OUTPUT_TEMPLATE)
	sed "s/PHP_VERSION/$$($(DOCKER_RUN) $(DOCKER_MIN_COMPOSER_PHP_VERSION_IMAGE_TAG) php -r 'echo PHP_VERSION;')/" \
		$(E2E_TEST_PASS_NO_CONFIG_MIN_COMPOSER_EXPECTED_OUTPUT_TEMPLATE) \
		> $@
$(E2E_TEST_PASS_NO_CONFIG_MIN_BOX_EXPECTED_OUTPUT): $(E2E_TEST_PASS_NO_CONFIG_MIN_BOX_EXPECTED_OUTPUT_TEMPLATE)
	sed "s/PHP_VERSION/$$($(DOCKER_RUN) $(DOCKER_MIN_BOX_PHP_VERSION_IMAGE_TAG) php -r 'echo PHP_VERSION;')/" \
		$(E2E_TEST_PASS_NO_CONFIG_MIN_BOX_EXPECTED_OUTPUT_TEMPLATE) \
		> $@

$(E2E_TEST_PASS_COMPLETE_PHAR): $(E2E_BOX_BIN)
	$(E2E_BOX) compile --ansi --working-dir=$(E2E_TEST_PASS_COMPLETE_DIR) --no-parallel
	touch -c $(E2E_TEST_PASS_COMPLETE_PHAR)
$(E2E_TEST_PASS_COMPLETE_PHAR): $(E2E_TEST_PASS_COMPLETE_DIR)/index.php $(E2E_TEST_PASS_COMPLETE_VENDOR)
$(E2E_TEST_PASS_COMPLETE_VENDOR): $(E2E_TEST_PASS_COMPLETE_DIR)/composer.lock
$(E2E_TEST_PASS_COMPLETE_DIR)/composer.lock: $(E2E_TEST_PASS_COMPLETE_DIR)/composer.json
$(E2E_TEST_PASS_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT): $(E2E_TEST_PASS_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT_TEMPLATE)
	sed "s/PHP_VERSION/$$($(DOCKER_RUN) $(DOCKER_MIN_COMPOSER_PHP_VERSION_IMAGE_TAG) php -r 'echo PHP_VERSION;')/" \
		$(E2E_TEST_PASS_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT_TEMPLATE) \
		> $@
$(E2E_TEST_PASS_COMPLETE_MIN_BOX_EXPECTED_OUTPUT): $(E2E_TEST_PASS_COMPLETE_MIN_BOX_EXPECTED_OUTPUT_TEMPLATE)
	sed "s/PHP_VERSION/$$($(DOCKER_RUN) $(DOCKER_MIN_BOX_PHP_VERSION_IMAGE_TAG) php -r 'echo PHP_VERSION;')/" \
		$(E2E_TEST_PASS_COMPLETE_MIN_BOX_EXPECTED_OUTPUT_TEMPLATE) \
		> $@

$(E2E_TEST_FAIL_COMPLETE_PHAR): $(E2E_BOX_BIN)
	$(E2E_BOX) compile --ansi --working-dir=$(E2E_TEST_FAIL_COMPLETE_DIR) --no-parallel
	touch -c $(E2E_TEST_FAIL_COMPLETE_PHAR)
$(E2E_TEST_FAIL_COMPLETE_PHAR): $(E2E_TEST_FAIL_COMPLETE_DIR)/index.php $(E2E_TEST_FAIL_COMPLETE_VENDOR)
$(E2E_TEST_FAIL_COMPLETE_VENDOR): $(E2E_TEST_FAIL_COMPLETE_DIR)/composer.lock
$(E2E_TEST_FAIL_COMPLETE_DIR)/composer.lock: $(E2E_TEST_FAIL_COMPLETE_DIR)/composer.json
$(E2E_TEST_FAIL_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT): $(E2E_TEST_FAIL_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT_TEMPLATE)
	sed "s/PHP_VERSION/$$($(DOCKER_RUN) $(DOCKER_MIN_COMPOSER_PHP_VERSION_IMAGE_TAG) php -r 'echo PHP_VERSION;')/" \
		$(E2E_TEST_FAIL_COMPLETE_MIN_COMPOSER_EXPECTED_OUTPUT_TEMPLATE) \
		> $@
$(E2E_TEST_FAIL_COMPLETE_MIN_BOX_EXPECTED_OUTPUT): $(E2E_TEST_FAIL_COMPLETE_MIN_BOX_EXPECTED_OUTPUT_TEMPLATE)
	sed "s/PHP_VERSION/$$($(DOCKER_RUN) $(DOCKER_MIN_BOX_PHP_VERSION_IMAGE_TAG) php -r 'echo PHP_VERSION;')/" \
		$(E2E_TEST_FAIL_COMPLETE_MIN_BOX_EXPECTED_OUTPUT_TEMPLATE) \
		> $@

$(E2E_TEST_SKIP_PHAR): $(E2E_TEST_FAIL_COMPLETE_PHAR)
$(E2E_TEST_SKIP_MIN_COMPOSER_EXPECTED_OUTPUT): $(E2E_TEST_SKIP_MIN_COMPOSER_EXPECTED_OUTPUT_TEMPLATE)
	sed "s/PHP_VERSION/$$($(DOCKER_RUN) $(DOCKER_MIN_COMPOSER_PHP_VERSION_IMAGE_TAG) php -r 'echo PHP_VERSION;')/" \
		$(E2E_TEST_SKIP_MIN_COMPOSER_EXPECTED_OUTPUT_TEMPLATE) \
		> $@
