build: false
platform:
  - x64
clone_folder: c:\projects\box
version: '{build}.{branch}'

environment:
  matrix:
  - dependencies: lowest
    php_ver_target: 7.1
  - dependencies: current
    php_ver_target: 7.2
  - dependencies: highest
    php_ver_target: 7.3

cache:
    - '%LOCALAPPDATA%\Composer\files'
    - composer.phar
    - C:\ProgramData\chocolatey\bin -> .appveyor.yml
    - C:\ProgramData\chocolatey\lib -> .appveyor.yml
    - c:\tools\php -> .appveyor.yml

init:
    - SET PATH=C:\Program Files\OpenSSL;c:\tools\php\%php_ver_target%;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET ANSICON=121x90 (121x90)
    - REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Command Processor" /v DelayedExpansion /t REG_DWORD /d 1 /f

install:
    - IF NOT EXIST c:\php mkdir c:\php
    - IF NOT EXIST c:\php\%php_ver_target% mkdir c:\php\%php_ver_target%
    - ps: appveyor-retry cinst --params '""/InstallDir:C:\tools\php\%php_ver_target%""' --ignore-checksums -y php --version ((choco search php --exact --all-versions -r | select-string -pattern $env:php_ver_target | sort { [version]($_ -split '\|' | select -last 1) } -Descending | Select-Object -first 1) -replace '[php|]','')
    - cd c:\tools\php\%php_ver_target%
    - copy php.ini-production php.ini /Y
    - echo date.timezone="UTC" >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - echo extension=php_mbstring.dll >> php.ini
    - echo extension=php_fileinfo.dll >> php.ini
    - cd c:\projects\box
    - IF NOT EXIST composer.phar (appveyor-retry appveyor DownloadFile https://github.com/composer/composer/releases/download/1.7.1/composer.phar)
    - php composer.phar self-update
    - IF %APPVEYOR_REPO_BRANCH%==master (SET COMPOSER_ROOT_VERSION=dev-master) ELSE (SET COMPOSER_ROOT_VERSION=%APPVEYOR_REPO_BRANCH%.x-dev)
    - IF %dependencies%==lowest appveyor-retry php composer.phar update --prefer-lowest --no-progress --ansi --no-suggest --prefer-dist -n
    - IF %dependencies%==current appveyor-retry php composer.phar update --no-progress --ansi --no-suggest --prefer-dist -n
    - IF %dependencies%==highest appveyor-retry php composer.phar update --no-progress -n --ansi --no-suggest --prefer-dist -n

test_script:
    - cd c:\projects\box
    - make test
