# Project info
site_name: Box Project
site_description: "Box: building and managing PHARs"
site_url: https://box-project.github.io/box
site_dir: dist/website

# Repository
repo_name: 'box-project/box'
repo_url: 'https://github.com/box-project/box'
edit_uri: ''

# Copyright
copyright: 'Box is licensed under <a href="https://github.com/box-project/box/blob/master/LICENSE">MIT license</a>'

# Document directory
docs_dir: doc

# Social Media
extra:
    social:
        -   icon: fontawesome/brands/github-alt
            link: https://github.com/box-project

# Configuration
theme:
    name: material
    logo: img/favicon.png
    favicon: img/favicon.png
    icon:
        repo: fontawesome/brands/github
    palette:
        scheme: default
        primary: brown
        accent: amber
    features:
        - content.tabs.link
        - navigation.tabs
        - navigation.top
    custom_dir: doc/overrides

nav:
    -   Home: index.md
    -   Documentation:
            -   Installation: installation.md
            -   Usage: usage.md
            -   Configuration: configuration.md
            -   'Requirements checker': requirement-checker.md
            -   'Optimize your PHAR': optimizations.md
            -   'PHAR code isolation': code-isolation.md
            -   'Docker support': docker.md
            -   'Symfony support': symfony.md
            -   'Reproducible builds': reproducible-builds.md
            -   'PHAR signing best practices': phar-signing.md
            -   'FAQ': faq.md

markdown_extensions:
    - admonition
    - attr_list
    - footnotes
    - pymdownx.highlight
    - pymdownx.superfences
    - toc:
        permalink: true

extra_css:
    - assets/announce.css
    - assets/docs.css
