#!/usr/bin/env php
<?php

/*
 * Generated by Humbug Box 4.x.x-dev.
 *
 * @link https://github.com/humbug/box
 */

Phar::mapPhar('box-auto-generated-alias-2268728bbb83.phar');

require 'phar://box-auto-generated-alias-2268728bbb83.phar/bin/check-requirements.php';

__HALT_COMPILER(); ?>
