<?php

declare(strict_types=1);

/*
 * This file is part of the box project.
 *
 * (c) Kevin Herrera <kevin@herrera.io>
 *     Théo Fidry <theo.fidry@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace KevinGH\Box\Composer;

use Composer\Factory;
use Composer\IO\NullIO;
use Humbug\PhpScoper\Autoload\ScoperAutoloadGenerator;
use RuntimeException;
use Throwable;
use const PHP_EOL;
use function KevinGH\Box\FileSystem\dump_file;
use function KevinGH\Box\FileSystem\file_contents;
use function preg_replace;
use function str_replace;

/**
 * @private
 */
final class ComposerOrchestrator
{
    private function __construct()
    {
    }

    /**
     * @param string[] $whitelist
     */
    public static function dumpAutoload(array $whitelist, string $prefix): void
    {
        try {
            $composer = Factory::create(new NullIO(), null, true);

            $installationManager = $composer->getInstallationManager();
            $localRepository = $composer->getRepositoryManager()->getLocalRepository();
            $package = $composer->getPackage();
            $composerConfig = $composer->getConfig();

            $generator = $composer->getAutoloadGenerator();
            $generator->setDevMode(false);
            $generator->setClassMapAuthoritative(true);

            $generator->dump($composerConfig, $localRepository, $package, $installationManager, 'composer', true);

            if ('' !== $prefix) {
                $autoloadFile = $composerConfig->get('vendor-dir').'/autoload.php';

                $autoloadContents = self::generateAutoloadStatements(
                    $whitelist,
                    $prefix,
                    file_contents($autoloadFile)
                );

                dump_file($autoloadFile, $autoloadContents);
            }
        } catch (Throwable $throwable) {
            throw new RuntimeException(
                'Could not dump the autoload: '.$throwable->getMessage(),
                $throwable->getCode(),
                $throwable
            );
        }
    }

    /**
     * @param string[] $whitelist
     */
    private static function generateAutoloadStatements(array $whitelist, string $prefix, string $autoload): string
    {
        if ([] === $whitelist) {
            return $autoload;
        }

        $whitelistStatements = (new ScoperAutoloadGenerator($whitelist))->dump($prefix);

        $whitelistStatements = preg_replace(
            '/(\\$loader \= .*)|(return \\$loader;)/',
            '',
            str_replace('<?php', '', $whitelistStatements)
        );

        $autoload = preg_replace(
            '/return (ComposerAutoloaderInit.+::getLoader\(\));/',
            <<<PHP
\$loader = \$1;

$whitelistStatements

return \$loader;
PHP
            ,
            $autoload
        );

        $autoload = str_replace(
            '// scoper-autoload.php @generated by PhpScoper',
            '// Whitelist statements @generated by PHP-Scoper',
            $autoload
        );

        return preg_replace(
            '/\n{2,}/m',
            PHP_EOL.PHP_EOL,
            $autoload
        );
    }
}
