#!/usr/bin/env bash

set -euf -o pipefail

readonly DOCKER=$(which docker)

# Globals
# PWD

if [[ "$(docker images -q box_php725 2> /dev/null)" == "" ]]; then
    $DOCKER build --platform=linux/amd64 --tag=box_php725 --file "$PWD/.docker/php725" .
fi

if [[ "$(docker images -q box_php81 2> /dev/null)" == "" ]]; then
    $DOCKER build --platform=linux/amd64 --tag=box_php81 --file "$PWD/.docker/php81" .
fi

if [[ "$(docker images -q box_php81_xdebug 2> /dev/null)" == "" ]]; then
    $DOCKER build --platform=linux/amd64 --tag=box_php81_xdebug --file "$PWD/.docker/php81_xdebug" .
fi
