<?php

declare(strict_types=1);

/*
 * This file is part of the box project.
 *
 * (c) Kevin Herrera <kevin@herrera.io>
 *     Théo Fidry <theo.fidry@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace KevinGH\Box;

use Assert\Assertion;
use Herrera\Annotations\Tokenizer;
use KevinGH\Box\Compactor\Php;

/**
 * Generates a new PHP bootstrap loader stub for a PHAR.
 */
final class StubGenerator
{
    /**
     * @var string The alias to be used in "phar://" URLs
     */
    private $alias;

    /**
     * @var null|string The top header comment banner text
     */
    private $banner = <<<'BANNER'

Generated by Box.

@link https://github.com/humbug/box

BANNER;

    /**
     * @var bool Embed the Extract class in the stub?
     */
    private $extract = false;

    /**
     * @var array The processed extract code
     */
    private $extractCode = [];

    /**
     * @var null|string The location within the PHAR of index script
     */
    private $index;

    /**
     * @var bool Use the Phar::interceptFileFuncs() method?
     */
    private $intercept = false;

    /**
     * @var string The shebang line
     */
    private $shebang = '#!/usr/bin/env php';

    /**
     * Creates a new instance of the stub generator.
     *
     * @return StubGenerator the stub generator
     */
    public static function create()
    {
        return new static();
    }

    /**
     * @return string The stub
     */
    public function generate(): string
    {
        $stub = [];

        if ('' !== $this->shebang) {
            $stub[] = $this->shebang;
        }

        $stub[] = '<?php';

        if (null !== $this->banner) {
            $stub[] = $this->getBannerStmt();
        }

        if ($this->extract) {
            $stub[] = implode("\n", $this->extractCode['constants']);

        }

        $stub = array_merge($stub, $this->getPharSectionStmts());

        if ($this->extract) {
            end($stub);

            $stub[key($stub)] .= ' else {';

            $stub = array_merge($stub, $this->getExtractSectionStmts());

            if ($this->index) {
                $stub[] = "require \"\$dir/{$this->index}\";";
            }

            $stub[] = '}';

            $stub[] = implode("\n", $this->extractCode['class']);
        }

        $stub[] = '__HALT_COMPILER();';

        return implode("\n", $stub);
    }

    public function alias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function banner(?string $banner): self
    {
        $this->banner = $banner;

        return $this;
    }

    public function extract(bool $extract): self
    {
        $this->extract = $extract;

        if ($extract) {
            $this->extractCode = [
                'constants' => [],
                'class' => [],
            ];

            $compactor = new Php(new Tokenizer());

            $file = __DIR__.'/Box_Extract.php';

            $code = file_get_contents($file);
            $code = $compactor->compact($file, $code);
            $code = preg_replace('/\n+/', "\n", $code);
            $code = explode("\n", $code);
            $code = array_slice($code, 2);

            foreach ($code as $i => $line) {
                if ((0 === strpos($line, 'use'))
                    && (false === strpos($line, '\\'))
                ) {
                    unset($code[$i]);
                } elseif (0 === strpos($line, 'define')) {
                    $this->extractCode['constants'][] = $line;
                } else {
                    $this->extractCode['class'][] = $line;
                }
            }
        }

        return $this;
    }

    public function index(?string $index): self
    {
        $this->index = $index;

        return $this;
    }

    public function intercept(bool $intercept): self
    {
        $this->intercept = $intercept;

        return $this;
    }

    public function shebang(string $shebang): self
    {
        Assertion::notEmpty($shebang, 'Cannot use an empty string for the shebang.');

        $this->shebang = $shebang;

        return $this;
    }

    /**
     * Escapes an argument so it can be written as a string in a call.
     *
     * @param string $arg
     * @param string $quote
     *
     * @return string The escaped argument
     */
    private function arg(string $arg, string $quote = "'"): string
    {
        return $quote.addcslashes($arg, $quote).$quote;
    }

    private function getAliasStmt(): ?string
    {
        return null !== $this->alias ? 'Phar::mapPhar('.$this->arg($this->alias).');' : null;
    }

    /**
     * @return string the processed banner
     */
    private function getBannerStmt(): string
    {
        // TODO: review how the banner is processed. Right now the doc says it can be a string
        // already enclosed in comments and if not it will be enclosed automatically.
        //
        // What needs to be done here?
        // - Test with a simple one liner banner
        // - Test with a banner enclosed in comments
        // - Test with a banner enclosed in phpdoc
        //
        // Then comes the question of multiline banners: I guess it works if contains `\n`?
        // Need tests for that anyway.
        //
        // Maybe a more user-friendly way to deal with multi-line banners would be to allow
        // an array of strings instead of just a string.
        //

        $banner = "/**\n * ";
        $banner .= str_replace(
            " \n",
            "\n",
            str_replace("\n", "\n * ", $this->banner)
        );

        $banner .= "\n */";

        return $banner;
    }

    /**
     * @return string[] The self extracting sections of the stub
     */
    private function getExtractSectionStmts(): array
    {
        return [
            '$extract = new Extract(__FILE__, Extract::findStubLength(__FILE__));',
            '$dir = $extract->go();',
            'set_include_path($dir . PATH_SEPARATOR . get_include_path());',
        ];
    }

    /**
     * @return string[] The sections of the stub that use the PHAR class
     */
    private function getPharSectionStmts(): array
    {
        $stub = [
            'if (class_exists(\'Phar\')) {',
        ];

        if (null !== $aliasStmt = $this->getAliasStmt()) {
            $stub[] = $aliasStmt;
        }

        if ($this->intercept) {
            $stub[] = 'Phar::interceptFileFuncs();';
        }

        if ($this->index) {
            $stub[] = "require 'phar://' . __FILE__ . '/{$this->index}';";
        }

        $stub[] = '}';

        return $stub;
    }
}
