# Fallback workflow to be able to have the branch protection enabled at all times.
name: Empty Benchmark Tests

on:
    # To be aware it need to be the counter-part of benchmark.yaml.
    push:
        branches: [ main ]

# See https://stackoverflow.com/a/72408109
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    # This is a "trick", a meta task which does not change, and we can use in
    # the protected branch rules as opposed to the tests one above which
    # may change regularly.
    validate-tests:
        name: Benchmark tests status
        runs-on: ubuntu-latest
        steps:
            - name: Successful run
              run: exit 0
