name: Build

on:
    push:
        branches: [ main ]
    pull_request:
    release:
        types: [ created ]

jobs:
    build-phar:
        runs-on: ubuntu-latest
        name: Build PHAR
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: phar.readonly=0
                    tools: composer
                    coverage: none

            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v2

            -   name: Install RequirementChecker Composer dependencies
                uses: ramsey/composer-install@v2
                with:
                    working-directory: 'requirement-checker'

            -   name: Build PHAR
                run: make compile

            # Smoke test
            -   name: Ensure the PHAR works
                run: bin/box.phar --version

            -   name: Ensure the PHAR is scoped
                run: bin/box.phar namespace | php -r 'if (!str_starts_with(stream_get_contents(STDIN), "_HumbugBox")) exit (1);'

            -   uses: actions/upload-artifact@v3
                name: Upload the PHAR artifact
                with:
                    name: box-phar
                    path: bin/box.phar

    publish-phar:
        runs-on: ubuntu-latest
        name: Publish the PHAR
        needs:
            - 'build-phar'
        if: github.event_name == 'release'
        steps:
            -   uses: actions/download-artifact@v3
                with:
                    name: box-phar
                    path: .

            -   name: Upload box.phar
                uses: softprops/action-gh-release@v1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    files: box.phar
