name: e2e

on:
    push:
        branches: [ master ]
    pull_request:

jobs:

    e2e:
        runs-on: ubuntu-latest
        name: ${{ matrix.e2e }} - ${{ matrix.php }}
        strategy:
            fail-fast: false
            matrix:
                e2e:
                    - 'e2e_php_settings_checker'
                    - 'e2e_scoper_alias'
                    - 'e2e_scoper_whitelist'
                    - 'e2e_check_requirements'
                    - 'e2e_symfony'
                    - 'e2e_composer_installed_versions'
                php: [ '7.3', '8.0' ]
                tools: [ 'composer:v2' ]

        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: "phar.readonly=0"
                    tools: ${{ matrix.tools }}
                    coverage: pcov

            -   name: Get composer cache directory
                id: composercache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache composer dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composercache.outputs.dir }}
                    key: composer-${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('composer.*') }}
                    restore-keys: |
                        composer-${{ runner.os }}-${{ matrix.php }}-
                        composer-${{ runner.os }}-
                        composer-

            -   name: Install dependencies
                run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

            -   name: Install requirement-checker dependencies
                run: composer install --no-interaction --no-progress --prefer-dist --working-dir requirement-checker

            -   name: Run e2e ${{ matrix.e2e }}
                run: make ${{ matrix.e2e }}
