name: Lint

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest
        name: CS
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
                    tools: composer
                    coverage: none

            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v2

            -   name: Ensure that the make target is up to date
                run: make vendor_install

            -   name: Install PHP-CS-Fixer
                uses: ramsey/composer-install@v2
                with:
                    working-directory: vendor-bin/php-cs-fixer

            -   name: Ensure that the PHP-CS-Fixer make target is up to date
                run: make php_cs_fixer_install

            -   run: make root_cs_lint
