name: PHAR DEBUG

on:
  push:
    branches: [ "main" ]
  pull_request: ~

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: regular check
        run: bin/box composer:check-version

      - name: PHP + regular check
        run: php bin/box composer:check-version

      - name: Test script
        run: bin/box composer:check-version --composer-bin=composer-test.php

      - name: PHP + Test script
        run: php bin/box composer:check-version --composer-bin=composer-test.php