name: PHAR DEBUG

on:
  push:
    branches: [ "main" ]
  pull_request: ~

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --working-dir=fixtures/build/dir018 --no-scripts

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-scripts

      - name: regular check
        run: composer dump-autoload