name: Security

on:
    push:
        branches: [ main ]
    pull_request: ~
    schedule:
        # Do not make it the first of the month and/or midnight since it is a very busy time
        - cron: "* 10 5 * *"
    release:
        types: [ created ]

jobs:
    security:
        runs-on: ubuntu-latest
        name: Audit Dependencies
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Cache the vulnerability database
                uses: actions/cache@v3
                id: cache-db
                with:
                    path: ~/.symfony/cache
                    key: db

            -   name: Checks dependencies for known vulnerabilities
                uses: symfonycorp/security-checker-action@v4
