name: Security Check

on:
    push:
        branches: [ main ]
    pull_request:
    release:
        types: [ created ]

jobs:
    security:
        runs-on: ubuntu-latest
        name: PHP Security Checker
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Cache the vulnerability database
                uses: actions/cache@v2
                id: cache-db
                with:
                    path: ~/.symfony/cache
                    key: db

            -   name: Checks dependencies for known vulnerabilities
                uses: symfonycorp/security-checker-action@v4
